### ISSUE TITLE
reproduce evaluation results

### ISSUE THREAD

**Issue by PruneTruong** [drinkingcoder/LIFE#1]
Hi, thanks for the great work! However, I can't reproduce your evaluation results. For example on KITTI-2012, I get AEPE pf 2.66 and Fl of 13.68 while in the paper you report 2.59 and 12.94 respectively. I am using the default parameters and the function Flow_estimator.estimate(target_img_numpy, source_img_numpy). 

Thanks

**Comment by drinkingcoder** [comment]
Hi, we also tried to re-evaluate the flow performance on KITTI with such API, but we get exactly the same results as we report in the paper. Could you provide more information?

**Comment by PruneTruong** [comment]
I use model = Flow_estimator(default) with 
default =  {'iters': 12,
                  'mixed_precision': True,
                  'small': False,
                  'model': 'third_party/LIFE/model/pretrain.pth'}

and then i get the flow = model.estimate(target_img_numpy, source_img_numpy). Here flow is shape 1x2xHxW numpy array and both images are numpy arrays of shape HxWx3, RGB. 

Do you see what might be the issue?

**Comment by panxkun** [comment]
Hi, we added the kitti evaluation script in the repo, you can use this [script](https://github.com/drinkingcoder/LIFE/blob/main/evaluation/kitti_eval.py) to test our model and check the difference with yours. The usage is also updated in [README.md](https://github.com/drinkingcoder/LIFE/blob/main/README.md)

**Comment by PruneTruong** [comment]
Ok i got it, it's because you're using 'image_0' as folder for KITTI-2012 whereas i am using 'colored_0', following FlowNet https://github.com/ClementPinard/FlowNetPytorch/blob/master/datasets/KITTI.py and and PWC-Net (https://github.com/philferriere/tfoptflow/blob/master/tfoptflow/dataset_kitti.py)!

**Comment by drinkingcoder** [comment]
Thanks for pointing this out! We refer to the evaluation code of RAFT for KITTI-2015, which uses `image_2', and directly transfer it to KITTI-2012. We'll correct these results in the next version and we believe this error doesn't impact the conclusion we achieved.
